name: CD

# Controls when the action will run. Triggers the workflow on push events for the main branch
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional message indicating that CD is disabled (can be removed)
      - name: CD Status
        run: echo 'CD is Disabled (Check workflow comment for the code).'

      # Deploy using SSH
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/home/kubil/app/encrypt-decrypt-keamanan-komputer
            git pull origin main
            pip install -r requirements.txt  # Install dependencies if needed
            python app.py  # Run your application
